export const REQUEST_INVENTORY = 'REQUEST_INVENTORY'
export const REQUEST_INVENTORY_SUCCESS = 'REQUEST_INVENTORY_SUCCESS'
export const REQUEST_INVENTORY_FAILURE = 'REQUEST_INVENTORY_FAILURE'

export const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY'
export const ADD_TO_INVENTORY_SUCCESS = 'ADD_TO_INVENTORY_SUCCESS'
export const ADD_TO_INVENTORY_FAILURE = 'ADD_TO_INVENTORY_FAILURE'

export const REQUEST_INVENTORY_ISSUE_REMOVE = 'REQUEST_INVENTORY_ISSUE_REMOVE'
export const REQUEST_INVENTORY_ISSUE_REMOVE_SUCCESS = 'REQUEST_INVENTORY_ISSUE_REMOVE_SUCCESS'
export const REQUEST_INVENTORY_ISSUE_REMOVE_FAILURE = 'REQUEST_INVENTORY_ISSUE_REMOVE_FAILURE'

// export const REQUEST_PERSONAL_INVENTORY = 'REQUEST_PERSONAL_INVENTORY'
// export const REQUEST_PERSONAL_INVENTORY_SUCCESS = 'REQUEST_PERSONAL_INVENTORY_SUCCESS'
// export const REQUEST_PERSONAL_INVENTORY_FAILURE = 'REQUEST_PERSONAL_INVENTORY_FAILURE'
//
// export const REQUEST_SELLING_INVENTORY = 'REQUEST_SELLING_INVENTORY'
// export const REQUEST_SELLING_INVENTORY_SUCCESS = 'REQUEST_SELLING_INVENTORY_SUCCESS'
// export const REQUEST_SELLING_INVENTORY_FAILURE = 'REQUEST_SELLING_INVENTORY_FAILURE'